# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e81c67f4f91075f3610817f4172e585a33e6b0ef86abd4c4254409cf64b5a4d266b882d0e728fc513c8c08aee6ad7b07c58e58b40ca45a98f636591a5085aba

test:
  secret_key_base: fa44c4a4d026e3ce3b66d974543dfe4d5aa73172ab995007b3de1f6da64bfc7bddb4aebf6bc0479a500fa6f7ddc8ef1600f088c1ea510bea7e6b4a1b6ab550f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
