Project.create([{ name: 'Lannister', description: '', start_date: '11-may-2015', end_date: '15-may-2015' }])
Project.create([{ name: 'Baratheon', description: '', start_date: '11-may-2015', end_date: '22-may-2015' }])
Project.create([{ name: 'Bolton', description: '', start_date: '4-may-2015', end_date: '15-may-2015' }])
Project.create([{ name: 'Florent', description: '', start_date: '4-may-2015', end_date: '22-may-2015' }])
Project.create([{ name: 'Martell', description: '', start_date: '11-may-2015', end_date: '15-may-2015' }])
Project.create([{ name: 'Redwyne', description: '', start_date: '11-may-2015', end_date: '15-may-2015' }])
Project.create([{ name: 'Stark', description: '', start_date: '11-may-2015', end_date: '15-may-2015' }])
Project.create([{ name: 'Umber', description: '', start_date: '11-may-2015', end_date: '15-may-2015' }])
Project.create([{ name: 'Targaryen', description: '', start_date: '18-may-2015', end_date: '29-may-2015' }])
Project.create([{ name: 'Tully', description: '', start_date: '25-may-2015', end_date: '29-may-2015' }])

Persona.create([{ name: 'Eddard', age: 25, gender: 'male', nationality: 'india', ethnicity: 'asian' }])
Persona.create([{ name: 'Catelyn', age: 25, gender: 'female', nationality: 'pakistan', ethnicity: 'asian' }])
Persona.create([{ name: 'Robb', age: 25, gender: 'male', nationality: 'india', ethnicity: 'asian' }])
Persona.create([{ name: 'Sansa', age: 25, gender: 'female', nationality: 'india', ethnicity: 'asian' }])
Persona.create([{ name: 'Arya', age: 25, gender: 'female', nationality: 'india', ethnicity: 'asian' }])
Persona.create([{ name: 'Bran', age: 25, gender: 'male', nationality: 'india', ethnicity: 'asian' }])
Persona.create([{ name: 'Rickon', age: 25, gender: 'male', nationality: 'india', ethnicity: 'asian' }])
